config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users ,:only => [:index, :new]
  resources :items
  resources :lecture_informations
  root 'top#index'

  get '/user/:id/items' => 'items#user_index'
  get '/:some' => 'contents#content'
  get '/:symbol/:certain' => 'contents#content'
  get '/items/new/ajax_change_college' => 'items#ajax_change_college'

end

app/models/lecture_information.rb
class LectureInformation < ActiveRecord::Base
  belongs_to :user
  belongs_to :college
  validates :name, presence: true
  validates :user_id, presence: true
  validates :teacher, presence: true
  validates :detail, presence: true
end

app/controllers/lecture_informations_controller.rb
class LectureInformationsController < ApplicationController
  before_action :set_lecture_information, only: [:show, :edit, :update, :destroy]
  layout 'af_log'
  # GET /lecture_informations
  # GET /lecture_informations.json
  def index
    @q = LectureInformation.search(params[:q])
    @lecture_informations = @q.result(distinct: true)
  end

  # GET /lecture_informations/1
  # GET /lecture_informations/1.json
  def show
  end

  # GET /lecture_informations/new
  def new
    @lecture_information = LectureInformation.new
  end

  # GET /lecture_informations/1/edit
  def edit
  end

  # POST /lecture_informations
  # POST /lecture_informations.json
  def create
    binding.pry
    @lecture_information = LectureInformation.new(lecture_information_params)

    respond_to do |format|
      if @lecture_information.save
        format.html { redirect_to @lecture_information, notice: 'Lecture information was successfully created.' }
        format.json { render :show, status: :created, location: @lecture_information }
      else
        format.html { render :new }
        format.json { render json: @lecture_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lecture_informations/1
  # PATCH/PUT /lecture_informations/1.json
  def update
    respond_to do |format|
      if @lecture_information.update(lecture_information_params)
        format.html { redirect_to @lecture_information, notice: 'Lecture information was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecture_information }
      else
        format.html { render :edit }
        format.json { render json: @lecture_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lecture_informations/1
  # DELETE /lecture_informations/1.json
  def destroy
    @lecture_information.destroy
    respond_to do |format|
      format.html { redirect_to lecture_informations_url, notice: 'Lecture information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture_information
      @lecture_information = LectureInformation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_information_params
      params.fetch(:lecture_information, {})
    end
end

app/helpers/lecture_informations_helper.rb
module LectureInformationsHelper
end

app/views/lecture_informations/_form.html.erb
<div class="form_left_fix">
<%= simple_form_for @lecture_information, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, label:'講義名' %>
  <%= f.input :detail, label:'詳細' %>
  <div class="form-group">
  <%= f.label :college_id, label:'配置学部', :class => "control-label"%>
  <%= f.collection_select :college_id, College.all, :id, :name,{},:class => "form-control",:prompt => "学部を選択してください。" %>
  </div>
  <%= f.input :teacher, label:'講師名' %>
  <div class="form-group" >
    <%= f.label :difficuty, label:'単位取得難易度', :class => 'control-label' %>
    <%= select :difficulty, :name, {"楽々" => 0, "楽" => 1,"普通" => 2, "難しい" => 3, "地獄" => 4},{:prompt => '受け渡し方法を選択してください。'}, {class: 'form-control' } %>
  </div>
  <div class="form-group" >
    <%= f.label :get_process, label:'主な単位取得方法', :class => 'control-label' %>
    <%= select :get_process, :name, {"テストのみ" => 0, "テストと出席" => 1,"出席のみ" => 2, "レポートのみ" => 3, "レポートと出席" => 4},{:prompt => '主な取得方法を選択してください。'}, {class: 'form-control' } %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id%>
  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                items_path, :class => 'btn btn-default' %>
<% end %>
</div>

app/views/lecture_informations/edit.html.erb
<h1>Editing Lecture Information</h1>

<%= render 'form' %>

<%= link_to 'Show', @lecture_information %> |
<%= link_to 'Back', lecture_informations_path %>

app/views/lecture_informations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lecture Informations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lecture_informations.each do |lecture_information| %>
      <tr>
        <td><%= link_to 'Show', lecture_information %></td>
        <td><%= link_to 'Edit', edit_lecture_information_path(lecture_information) %></td>
        <td><%= link_to 'Destroy', lecture_information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture information', new_lecture_information_path %>

app/views/lecture_informations/new.html.erb
<div class="row">
  <section class="col-lg-6">
<div class="page-header">
  <h1>講義情報を投稿</h1>
</div>
<%= render :partial => 'form' %>
  </section>
  </div>

app/views/lecture_informations/show.html.erb
<div class="row">
  <section class="col-lg-8">
    <dl class="lecture_dl">
      <div class="item_head">
        <dt class="lecture">
        <%= @lecture_information.name %>
        </dt>
        <dd class="college">
        <span><%= @lecture_information.college.university.name%></span>
        <span><%= @lecture_information.college.name%></span>
        </dd><!-- /.college -->
      </div>
      <dd>
      <dl>
        <dt class="subject">
        <span>作成者  <%= @lecture_information.user.name%>さん</span>
        </dt>
        <!-- /.subject -->
        <dd class="apartContents">
        <div><div><div><div><div>
                  <div>
                    <div class="year"><div><div><div><div>
                              <dl>
                                <dt>教授名</dt>
                                <dd><%= @lecture_information.teacher %></dd>
                              </dl>
                            </div></div></div></div></div><!-- /.year -->
                    <div class="item_price"><div><div><div><div>
                                      <dl>
                                        <dt>難易度</dt>
                                        <dd><%= @lecture_information.difficulty%></dd>
                                      </dl>
                                    </div></div></div></div></div><!-- /.item_price -->
                  </div>
                  <div class="apartBox">
                    <div class="test"><div><div><div><div>
                              <dl>
                                <dt>詳細</dt>
                                <dd>
                                <p>
                                  <%= @lecture_information.detail %>
                                </p>
                                </dd>
                              </dl>
                            </div></div></div></div></div><!-- /.test -->
                  </div><!-- /.apartBox -->
                </div></div></div></div></div>
        </dd><!-- /.apartContents -->
      </dl>
      </dd>
    </dl>

    <%= link_to '戻る', :back ,:class => 'btn btn-default'  %>
    <% if @lecture_information.user_id == current_user.id %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
        edit_lecture_information_path(@lecture_information), :class => 'btn btn-default' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
        lecture_informations_path,
        :method => 'delete',
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
        :class => 'btn btn-danger' %>
    <% end %>
</section>
<section class="col-lg-4">
  <div>広告</div>
</section>
</div>
<%= link_to 'Edit', edit_lecture_information_path(@lecture_information) %> |
<%= link_to 'Back', lecture_informations_path %>